# Javascript Node CircleCI 2.0 configuration file
# I think you would love to check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# * Emmsdan
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: e627a844f34fc4cabbd0a17ab90a544a0ba2b301ea251f12b336e2973be7154c
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: 
          name: Installing Dependecies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install code climate test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # run tests!
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            yarn run test:cov
            ./cc-test-reporter after-build --exit-code $?
